'''
Created on 26/08/2014

@author: Aitor Gomez Goiri
'''

import unittest
from Crypto.Hash.SHA256 import SHA256Hash
from lightsec.helpers import BaseStationHelper, SensorHelper, UserHelper
from lightsec.tools.key_derivation import KeyDerivationFunctionFactory, Nist800
from lightsec.tools.encryption import AESCTRCipher


class HelpersTest(unittest.TestCase):
    
    def setUp(self):
        self.kdf_factory = KeyDerivationFunctionFactory( Nist800, SHA256Hash(), 256 ) # 512 ) 
        self.base_station = BaseStationHelper( self.kdf_factory )
        self.base_station.install_secret("sensor1", "authms1", "encms1")
    
    def test_encryption(self):
        stuff = self.base_station.create_keys( "user1", "sensor1", 10 )
        self.sensor = SensorHelper( self.kdf_factory,
                                    AESCTRCipher, "authms1", "encms1" )
        
        user = UserHelper("sensor1", stuff["kauth"], stuff["kenc"], AESCTRCipher)
        ciphertext = user.encrypt("test")
        
        # test that same keys are generated by the base station and the sensor
        kenc, kauth = self.sensor.create_keys( "user1", stuff["a"], stuff["init_time"], stuff["exp_time"], user.initial_counter )
        self.assertSequenceEqual( kenc, stuff["kenc"] )
        self.assertSequenceEqual( kauth, stuff["kauth"] )
        
        # test that the sensor is now able to understand the first message sent by the user
        self.sensor_cipher = AESCTRCipher(user.initial_counter, kenc)
        deciphertext = self.sensor_cipher.encrypt(ciphertext)
        self.assertSequenceEqual(deciphertext, "test")
        


if __name__ == "__main__":
    #import sys;sys.argv = ['', 'Test.testName']
    unittest.main()